repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: .venv/Scripts/python.exe -m ruff check --fix
        language: system
        pass_filenames: true
        types: [python]
      - id: ruff-format
        name: ruff format
        entry: .venv/Scripts/python.exe -m ruff format
        language: system
        pass_filenames: true
        types: [python]
